# CO2 Constants
CO2_PER_KWH_COAL = 800  # grams
CO2_PER_KWH_NATURAL_GAS = 490
CO2_PER_KWH_RENEWABLE = 50
CO2_PER_KWH_AVERAGE_INDIA = 700

# Petrol car emissions
CO2_PETROL_PER_KM = 230  # grams/km

# Tree CO2 absorption (kg/year)
NEEM_TREE_CO2_ABSORPTION = 22
BANYAN_TREE_CO2_ABSORPTION = 19
PEEPAL_TREE_CO2_ABSORPTION = 24
BAMBOO_CO2_ABSORPTION = 28

# Default values
DEFAULT_VEHICLE_EFFICIENCY = 0.14  # kWh/km
DEFAULT_BATTERY_CAPACITY = 60  # kWh

# Air quality thresholds
AQI_GOOD_THRESHOLD = 50
AQI_MODERATE_THRESHOLD = 100
AQI_UNHEALTHY_SENSITIVE_THRESHOLD = 150
AQI_UNHEALTHY_THRESHOLD = 200

# Eco score weights
ECO_SCORE_DRIVING_EFFICIENCY_WEIGHT = 0.30
ECO_SCORE_ROUTE_CLEANLINESS_WEIGHT = 0.25
ECO_SCORE_CHARGING_GREENNESS_WEIGHT = 0.25
ECO_SCORE_MAINTENANCE_WEIGHT = 0.20

# Badge thresholds
BADGE_CARBON_NEUTRAL_WEEK = 50  # kg CO2 saved
BADGE_TREE_PLANTER = 25  # trees equivalent
BADGE_RENEWABLE_CHARGER_COUNT = 10  # times charged during renewable peak
BADGE_AIR_QUALITY_ADVOCATE_COUNT = 20  # times chose clean routes

# Currencies
DEFAULT_CURRENCY = "INR"
DEFAULT_TIMEZONE = "Asia/Kolkata"
